### PR TITLE
Constellation logo resizing

### PR DESCRIPTION
**Pull request by digitaltwinnn**
Larger logos (blue) to also support high resolution screens. Resizes across resolutions. Both horizontally and vertically centered on the downloading / loading page.

### CODE REVIEW

**Comment by digitaltwinnn** [comment]
Ok thanks! I found a nice collection with logos and added them to the /img folder: https://constellationnetwork.io/resources/media-kit/

Previously I took it from the official constellation github which appears to be outdated, may want to remove/update that one: https://github.com/Constellation-Labs/visual-identity

**Comment by grvlle** [comment]
Realized I screwed up the first screenshot.



Notice the increased hight on this.

**Comment by digitaltwinnn** [comment]
Thanks again! The new logo had a lot of empty space around so I cropped it now

**Comment by grvlle** [comment]
Absolutely perfect!

**Pull request merged**
