### PR TITLE
Fix vuex state mgmt

### PR DESCRIPTION
**Pull request by digitaltwinnn**
Separated the vuex store into different modules. This also enforces the use of $store.commit(...) across the wallet (all these state mutations now appear in Vue devtools as well). Fixes to keep the store in sync with the backend. Improvements to reset the state to its original when navigating / logging out without risk of missing attributes.

### CODE REVIEW

**Comment by digitaltwinnn** [comment]
> Initial feedback:
> Running into this on Windows generates below error.

Ok thanks, I actually thought that I already fixed it with this commit which previously got the same error, but that was for empty txhistory, so I'll continue to look into it as well. https://github.com/grvlle/constellation_wallet/pull/105/commits/4d9fab8bcf545ddf5f55cc5760cd425d04e3a8d4

**Comment by digitaltwinnn** [comment]
> Also noticed that when I log out of dark mode, I return to a bright login screen.

Yes this is actually 'expected' now because of the state mgmt. fixes. The darkmode state is stored on the wallet so it can't be known yet at the login. Previously this state 'leaked' into this page after a previous login.


If we want darkmode consistently across all wallet we need to store it in a 'application' entity rather than on the individual wallets. Same can be said for 'terms of service', with 2 wallets you need to accept it twice while perhaps once is enough. That would allow us also to move this check even earlier during the login process and ask the user before they login instead of after

**Comment by grvlle** [comment]
> > Also noticed that when I log out of dark mode, I return to a bright login screen.
> 
> Yes this is actually 'expected' now because of the state mgmt. fixes. The darkmode state is stored on the wallet so it can't be known yet at the login. Previously this state 'leaked' into this page after a previous login.
> 
> If we want darkmode consistently across all wallet we need to store it in a 'application' entity rather than on the individual wallets. Same can be said for 'terms of service', with 2 wallets you need to accept it twice while perhaps once is enough. That would allow us also to move this check even earlier during the login process and ask the user before they login instead of after

That makes sense. I've been thinking on having dark mode be an application setting, rather than a wallet setting which is the more common thing for applications I think. But the downsides of that is the inability to separate between two or more keys on your system. With more themes introduced I envisioned that you could have a "red" key, and a "blue" key and these would be immediately recognized when logged in as the theme would reflect the key that one is logged in with. 

But I'd be open to change that, since there are means of uploading photos and wallet tags which practically does the same thing, but less intrusive. If you think we should consider it application state, then I'm all for it.

**Comment by digitaltwinnn** [comment]
> But the downsides of that is the inability to separate between two or more keys on your system.

Yeah I agree. I'll pass the darkmode along during the logout as a navigation property so that the loginpage can specifically check against that.

**Pull request merged**
